# -*- coding: utf-8 -*-
from pathlib import Path
import re, subprocess
root = Path(r"D:\xian-shang-you-wei")
main = (root/"backend/main.py").read_text(encoding="utf-8")
idx = (root/"backend/frontend/index.html").read_text(encoding="utf-8")
lt = (root/"backend/frontend/landing.html").read_text(encoding="utf-8")
fails=[]
def ok(c,m):
    print(("OK" if c else "FAIL"), m)
    if not c: fails.append(m)
ok(re.search(r"GUEST_DAILY_LIMIT\s*=\s*3", main) is not None, "GUEST=3")
ok(re.search(r"FREE_DAILY_LIMIT\s*=\s*5", main) is not None, "FREE=5")
ok("def _check_daily_credit" in main and "def _consume_daily_credit" in main and "def _is_premium" in main, "helpers")
ok("Depends(require_user)" not in (re.search(r"def get_chips\([\s\S]{0,200}", main).group(0) if re.search(r"def get_chips\(", main) else ""), "chips optional")
ok("Depends(require_user)" not in (re.search(r"def get_kline\([\s\S]{0,200}", main).group(0) if re.search(r"def get_kline\(", main) else ""), "kline optional")
ok("Depends(get_current_user)" in re.search(r"def get_opening_picks\([\s\S]{0,120}", main).group(0), "opening user")
do = re.search(r"def _do_analyze\([\s\S]*?\n(?:def |@app\.)", main)
ok(do and "_inc_query_count" not in do.group(0) and "_consume_daily_credit" not in do.group(0), "_do_analyze no inc")
pf = re.search(r"async def portfolio_analysis\([\s\S]*?return \{\"ok\": True, \"data\": results\}", main)
ok(pf and "_consume_portfolio_daily_credit" in pf.group(0), "portfolio consume")
rg = re.search(r"def report_generate\([\s\S]*?current_basis", main)
ok(rg and "_check_daily_credit" in rg.group(0) and "_consume_daily_credit" in main[main.find("def report_generate"):main.find("def report_generate")+2500], "report daily_credit")
ok("_taipeiDayKey" in idx and "_syncCreditFromPayload" in idx, "FE helpers")
ok("guest_day_'+new Date().toISOString" not in idx, "no UTC guest_day")
ok("parseInt(localStorage.getItem(_gk)||'0',10)>=1" not in idx, "no FE>=1 wall")
ok("上次更新（台北）" in idx, "WaveA updated_at")
ok("showUpgradeModal" in re.search(r"function goPayFromApp\(plan\) \{[\s\S]*?\n\}", idx).group(0), "WaveA goPay")
ok("doUpgrade" not in re.search(r"function goPayFromApp\(plan\) \{[\s\S]*?\n\}", idx).group(0), "no fake doUpgrade")
ok(".pay-done .nav-cta" in lt and ".pay-done .hero-btns" not in lt, "WaveA pay-done CSS")
ok("j.preview" in idx, "FE preview note")
print("SELFTEST", "FAIL" if fails else "OK", len(fails))
r=subprocess.run(["git","diff","--stat","backend/main.py","backend/frontend/index.html","backend/frontend/landing.html"], cwd=str(root), capture_output=True, text=True)
print(r.stdout)
