# -*- coding: utf-8 -*-
from pathlib import Path
t = Path(r"D:\xian-shang-you-wei\backend\main.py").read_text(encoding="utf-8")
i = t.find("def _deep_is_premium")
print("===DEEP_IS===")
print(t[i:i+900])
i = t.find("def api_deep_analysis")
print("===API_DEEP===")
print(t[i:i+2200])
i = t.find("def report_generate")
print("===REPORT===")
print(t[i:i+1400])
i = t.find("async def portfolio_analysis")
print("===PF===")
print(t[i:i+500])
i = t.find("if is_paid:\n            post[\"content\"]")
print("===FORUM===", i)
print(t[i:i+200] if i>=0 else "no is_paid content")
i = t.find("def auth_me")
print("===ME===")
print(t[i:i+400])
i = t.find("def forum_get_post")
print("===FORUM_GET===")
print(t[i:i+800] if i>=0 else "no")
