(()=>{'use strict';
const $=id=>document.getElementById(id),api=MarketData,V=MarketVisuals,L=MarketLayout,esc=V.esc;
const scene=V.create($('galaxy')),expandedScene=V.create($('expandedGalaxy'));
const ROUTES=Object.freeze({stock:'/stock/?stock={code}',selection:'/stock/?page=multisignal',disposition:'/disposal.html',discussion:'/stock/?page=forum'});
const media=matchMedia('(prefers-color-scheme: dark)'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
const mobile=()=>innerWidth<=760,missing='資料準備中',num=(n,suffix='')=>n==null?missing:Number(n).toLocaleString('zh-TW')+suffix,fmt=n=>n==null?missing:(n>0?'+':'')+n.toFixed(2)+'%',share=n=>n==null?missing:(n*100).toFixed(1)+'%';
let overview,timeline,index=0,dayGroups=[],maxScores={},referenceShares={},layoutKey='',expandedKey='',expandedId=null,selected=null,detailData=null,lastFocus=null,loadId=0,detailRequest=0,builds=0,transitions=0,lite=false,playing=null,poll=null,resizeTimer=null,hoverId=null;
const detailCache=new Map(),snapshot=()=>timeline?.snapshots[index];
let preference='system';try{preference=localStorage.getItem('market-v2-theme')||'system'}catch(e){}
function applyTheme(value){preference=value;document.documentElement.dataset.theme=value==='system'?(media.matches?'dark':'light'):value;try{localStorage.setItem('market-v2-theme',value)}catch(e){}$('themeChoice').value=value;$('theme').setAttribute('aria-label',document.documentElement.dataset.theme==='dark'?'切換淺色主題':'切換深色主題')}
$('theme').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('themeChoice').onchange=e=>applyTheme(e.target.value);media.addEventListener('change',()=>applyTheme(preference));applyTheme(preference);
function setLite(value){lite=!!value;document.body.classList.toggle('lite',lite);$('lite').setAttribute('aria-pressed',String(lite));layoutKey='';expandedKey='';if(snapshot())renderScene(true)}
$('lite').onclick=()=>setLite(!lite);reduce.addEventListener('change',e=>setLite(e.matches));setLite(reduce.matches||(navigator.deviceMemory&&navigator.deviceMemory<=4)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4));
$('settingsToggle').onclick=()=>{$('settings').hidden=!$('settings').hidden;$('settingsToggle').setAttribute('aria-expanded',String(!$('settings').hidden))};
function ranks(groups){return [...groups].sort((a,b)=>(a.stable_rank??Infinity)-(b.stable_rank??Infinity)||b.activity_score-a.activity_score||a.group_id.localeCompare(b.group_id))}
function clusterShares(groups,provided=null){const result={};for(const id of new Set(dayGroups.map(g=>g.cluster_id))){const direct=provided?.find(c=>(c.cluster_id||c.id)===id),members=groups.filter(g=>g.cluster_id===id);result[id]=direct?.turnover_share??(members.length&&members.every(g=>g.turnover_share!=null)?members.reduce((s,g)=>s+g.turnover_share,0):null)}return result}
function chosenCluster(){return dayGroups.find(g=>g.group_id===selected)?.cluster_id}
function renderScene(instant=false){if(!snapshot())return;const width=Math.round($('sceneWrap').clientWidth);if(width<100)return;const key=[overview.demo_scenario,width,mobile(),lite].join('|');if(key!==layoutKey){const layout=L.solve({groups:dayGroups,maxScores,width,mobile:mobile(),clusterShares:referenceShares,focusClusters:[...new Set(timeline.snapshots.flatMap(s=>ranks(s.groups).slice(0,5).map(g=>g.cluster_id)))]});scene.build(layout,lite,mobile());builds++;layoutKey=key;instant=true;renderStrip(true)}
 scene.update(snapshot().groups,overview.change_scale,{instant});scene.shares(clusterShares(snapshot().groups,snapshot().clusters||(index===timeline.snapshots.length-1?overview.clusters:null)));scene.select(selected,chosenCluster());renderStrip();renderExpanded(instant);$('visibleCount').textContent=snapshot().groups.length+' 個族群 · '+(mobile()?'點小星團可展開':'點星球看詳情');hideHover();}
function renderStrip(build=false){const strips=scene.getLayout()?.strip||[];if(build){$('clusterStrip').style.gridTemplateColumns='repeat('+Math.max(1,Math.min(strips.length,scene.getLayout().stripColumns))+',minmax(0,1fr))';$('clusterStrip').innerHTML=strips.map(c=>`<button class="cluster-mini" data-cluster="${esc(c.clusterId)}" aria-expanded="false"><span class="mini-space"><i></i></span><strong>${esc(c.name)}</strong><small></small></button>`).join('')}
 for(const button of $('clusterStrip').querySelectorAll('button')){const gs=snapshot().groups.filter(g=>g.cluster_id===button.dataset.cluster),valid=gs.length&&gs.every(g=>g.turnover!=null&&g.avg_change_pct!=null),turn=gs.reduce((s,g)=>s+(g.turnover??0),0),change=valid&&turn>0?gs.reduce((s,g)=>s+g.turnover*g.avg_change_pct,0)/turn:null,r=L.radius(Math.min(100,gs.reduce((s,g)=>s+(g.activity_score??0),0)),true,.55),key=V.bucket(change,overview.change_scale).key;button.querySelector('i').style.cssText=`width:${r*2}px;height:${r*2}px;background:var(--${key}-top)`;button.querySelector('small').textContent=change==null?'資料不足 · 展開':'展開 '+gs.length+' 群';button.setAttribute('aria-expanded',String(button.dataset.cluster===expandedId));button.classList.toggle('dim',!!selected&&button.dataset.cluster!==chosenCluster())}}
$('clusterStrip').onclick=e=>{const b=e.target.closest('button');if(!b)return;expandedId=expandedId===b.dataset.cluster?null:b.dataset.cluster;expandedKey='';renderExpanded(true);renderStrip();if(expandedId)$('collapseCluster').focus()};
$('collapseCluster').onclick=()=>{const id=expandedId;expandedId=null;expandedKey='';$('clusterExpand').hidden=true;$('clusterStrip').querySelector(`[data-cluster="${CSS.escape(id)}"]`)?.focus();renderStrip()};
function renderExpanded(instant=false){$('clusterExpand').hidden=!expandedId;if(!expandedId)return;const width=Math.round($('sceneWrap').clientWidth),key=[expandedId,width,mobile(),lite].join('|');if(expandedKey!==key){expandedScene.build(L.solve({groups:dayGroups.filter(g=>g.cluster_id===expandedId),maxScores,width,mobile:mobile(),expanded:true}),lite,mobile());expandedKey=key;instant=true}expandedScene.update(snapshot().groups,overview.change_scale,{instant});expandedScene.shares(clusterShares(snapshot().groups,snapshot().clusters));expandedScene.select(selected,chosenCluster())}
function renderSummary(){const s=overview.market_summary,joined=(values,format)=>values.every(v=>v==null)?missing:values.map(format).join(' / ');$('summaryBar').innerHTML=[['加權指數',s.index_value==null&&s.index_change_pct==null?missing:num(s.index_value)+' / '+fmt(s.index_change_pct)],['市場成交',s.market_turnover==null?missing:num(s.market_turnover/1e8,' 億元')],['上漲 / 下跌 / 平盤',joined([s.up_count,s.down_count,s.flat_count],v=>num(v))],['摘要時間',s.data_time??missing]].map(([label,value])=>`<div><small>${label}</small><strong>${esc(value)}</strong></div>`).join('')}
function renderHighlights(){const gs=snapshot()?.groups||[],list=(title,items)=>`<section><h2>${title}</h2>${items.length?items.map((g,i)=>`<button class="highlight-row" data-group="${esc(g.group_id)}"><span class="rank">${i+1}</span><strong>${esc(g.name)}</strong><span class="${V.bucket(g.avg_change_pct,overview.change_scale).side}">${esc(fmt(g.avg_change_pct))}</span><small>活躍 ${esc(g.activity_score)}${esc(g.activity_change>0?' · 升溫 +'+g.activity_change:'')}</small></button>`).join(''):'<p class="detail-note">此刻無</p>'}</section>`;
 $('highlightLists').innerHTML=list('焦點前 5',ranks(gs).slice(0,5))+(mobile()?'':list('升溫最快',gs.filter(g=>g.activity_change>0).sort((a,b)=>b.activity_change-a.activity_change||a.group_id.localeCompare(b.group_id)).slice(0,3))+list('跌最重',gs.filter(g=>g.avg_change_pct<0).sort((a,b)=>a.avg_change_pct-b.avg_change_pct||a.group_id.localeCompare(b.group_id)).slice(0,3)));$('highlightLists').hidden=!!selected&&!mobile();}
$('highlightLists').onclick=e=>{const b=e.target.closest('[data-group]');if(b)openDetail(b.dataset.group,b)};
function renderWatch(){const list=overview.watchlist;$('watchStrip').innerHTML='<h2>☆ 我的自選</h2>'+(list==null?`<p>${missing}</p>`:!list.length?'<p>尚未加入自選股</p>':list.map(s=>`<button data-route="stock" data-code="${esc(s.code)}" class="watch-item ${selected&&s.group_ids?.includes(selected)?'linked':''}"><strong>${esc(s.name)}</strong><small>${esc(s.code)}</small><b>${esc(num(s.price,' 元'))}</b><span class="${V.bucket(s.change_pct,overview.change_scale).side}">${esc(fmt(s.change_pct))}</span></button>`).join(''))+`<small>摘要時間 ${esc(overview.watchlist_data_time??missing)} · 不隨回放</small>`}
function renderLegend(){const s=overview.change_scale;$('scaleLegend').innerHTML=[['flat','平盤 < '+s.flat],['up-1',s.flat+'–'+s.small],['up-2',s.small+'–'+s.normal],['up-3',s.normal+'–'+s.strong],['up-4','≥ '+s.strong]].map(([k,v])=>`<span><i style="background:var(--${k}-top)"></i>${esc(v)}%</span>`).join('');$('legend').open=!mobile()}
function stop(){clearInterval(playing);playing=null;$('play').textContent='▶';$('play').setAttribute('aria-label','播放回放')}
function renderSnapshot(instant=false){const s=snapshot();if(!s)return;$('dataTime').textContent=s.time;$('timeOutput').textContent=s.time;$('timeline').value=index;$('timeline').setAttribute('aria-valuetext',s.time);$('replayState').textContent='快照 '+s.time;const g=ranks(s.groups)[0];$('currentFocus').innerHTML=g?`<time>${esc(s.time)}</time><b>${esc(g.name)}</b><span class="${V.bucket(g.avg_change_pct,overview.change_scale).side}">${esc(fmt(g.avg_change_pct))}</span>`:'此時段無族群資料';$('timeCursor').style.left=(index/Math.max(1,timeline.snapshots.length-1)*100)+'%';$('source').textContent=overview.source+' · '+overview.trade_date+' '+s.time;renderScene(instant);renderHighlights();if(selected&&detailData)renderDetail()}
function setIndex(value){if(!timeline?.snapshots.length)return;index=Math.max(0,Math.min(timeline.snapshots.length-1,Number(value)));renderSnapshot()}
$('timeline').oninput=e=>{stop();setIndex(e.target.value)};$('previous').onclick=()=>{stop();setIndex(index-1)};$('next').onclick=()=>{stop();setIndex(index+1)};$('latest').onclick=()=>{stop();setIndex(timeline.snapshots.length-1)};
$('play').onclick=()=>{if(playing){stop();return}if(!timeline?.snapshots.length)return;if(index===timeline.snapshots.length-1)setIndex(0);$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','暫停回放');playing=setInterval(()=>{if(index>=timeline.snapshots.length-1){stop();return}setIndex(index+1)},1200)};
function renderRotation(){const snaps=timeline.snapshots,N=snaps.length,svg=$('rotationBand'),bandWidth=Math.max(200,Math.round($('rotationBand').clientWidth)),bandHeight=mobile()?120:160;$('timeline').max=Math.max(0,N-1);for(const id of ['timeline','play','previous','next','latest'])$(id).disabled=!N;$('snapshotStep').textContent=timeline.interval_min+' 分鐘快照';$('startTime').textContent=snaps[0]?.time||'—';$('endTime').textContent=snaps.at(-1)?.time||'—';$('focusStops').innerHTML='';svg.setAttribute('viewBox','0 0 '+bandWidth+' '+bandHeight);svg.setAttribute('preserveAspectRatio','none');
 const candidates=dayGroups.map(g=>({id:g.group_id,name:g.name,max:Math.max(-1,...snaps.map(s=>s.groups.find(n=>n.group_id===g.group_id)?.turnover_share??-1))})).filter(g=>g.max>=0).sort((a,b)=>b.max-a.max||a.id.localeCompare(b.id)).slice(0,mobile()?4:6);
 // One close-time value (real 09/24 13:35) is not a rotation; require half the day to carry shares.
 const covered=snaps.filter(s=>s.groups.some(g=>g.turnover_share!=null)).length,fallback=!candidates.length||covered<N/2;svg.dataset.mode=fallback?'missing':'share';$('rotationNote').textContent=fallback?'成交占比資料準備中。以下為領先族群漲跌色帶，不代表成交占比。':'帶寬＝成交占比（族群可能重疊）；顏色＝前後各 2 筆平均漲跌。斜線表示缺資料。';
 let html='<defs><pattern id="missingHatch" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="var(--muted)" opacity=".4"/></pattern></defs>',labels=[];const maxTotal=Math.max(1e-6,...snaps.map(s=>candidates.reduce((v,c)=>v+(s.groups.find(g=>g.group_id===c.id)?.turnover_share??0),0))),unit=(bandHeight-20)/maxTotal;
 if(fallback){html+='<rect width="'+bandWidth+'" height="'+bandHeight+'" fill="url(#missingHatch)"/>';for(let i=0;i<N;i++){const g=ranks(snaps[i].groups)[0];if(g)html+=`<rect x="${i/N*bandWidth}" y="${bandHeight*.35}" width="${bandWidth/N+.2}" height="${bandHeight*.45}" fill="var(--${V.bucket(g.avg_change_pct,overview.change_scale).key}-top)"/>`}const runs=[];snaps.forEach((s,i)=>{const g=ranks(s.groups)[0];if(!g)return;if(!runs.length||runs.at(-1).id!==g.group_id)runs.push({id:g.group_id,start:i,end:i,name:g.name});else runs.at(-1).end=i});$('focusStops').innerHTML=runs.map(r=>`<button class="focus-stop" data-index="${r.start}"><time>${esc(snaps[r.start].time)}</time><strong>${esc(r.name)}</strong></button>`).join('')}
 else{const sums=Array(N).fill(0);for(const c of candidates){let best=null;for(let i=0;i<N;i++){const g=snaps[i].groups.find(g=>g.group_id===c.id),x=i/N*bandWidth,w=bandWidth/N+.2;if(g?.turnover_share==null){html+=`<rect x="${x}" width="${w}" height="${bandHeight}" fill="url(#missingHatch)"/>`;continue}const samples=snaps.slice(Math.max(0,i-2),i+3).map(s=>s.groups.find(g=>g.group_id===c.id)?.avg_change_pct).filter(n=>n!=null),change=samples.length?samples.reduce((s,n)=>s+n,0)/samples.length:null,h=g.turnover_share*unit,y=bandHeight-5-sums[i]-h;sums[i]+=h;html+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="var(--${V.bucket(change,overview.change_scale).key}-top)"/>`;if(!best||h>best.h)best={x:x+w/2,y:y+h/2,h}}
 if(best)labels.push({...best,name:c.name})}
 // HTML legend preserves legibility on narrow screens; SVG names sit at peak width.
 const placed=[];for(const b of labels.sort((a,b)=>b.h-a.h)){const w=L.measure(b.name,11),x=Math.min(bandWidth-w/2-3,Math.max(w/2+3,b.x)),y=b.y+4,box={x:x-w/2,y:y-11,w,h:14};if(!placed.some(p=>box.x<p.x+p.w+3&&box.x+box.w+3>p.x&&box.y<p.y+p.h+3&&box.y+box.h+3>p.y)){html+=`<text x="${x}" y="${y}" text-anchor="middle" class="rotation-label">${esc(b.name)}</text>`;placed.push(box)}}
 $('focusStops').innerHTML=candidates.map(c=>`<span class="rotation-key">${esc(c.name)}</span>`).join('')}
 svg.innerHTML=html;
}
$('focusStops').onclick=e=>{const b=e.target.closest('[data-index]');if(b){stop();setIndex(b.dataset.index)}};
const counts=g=>[g.up_count,g.down_count,g.flat_count].every(n=>n==null)?missing:[g.up_count,g.down_count,g.flat_count].map(n=>num(n)).join(' / ');
function hideHover(){hoverId=null;$('hoverCard').hidden=true}
function stats(g){return `<div class="detail-kicker">${esc(g.cluster_name)}</div><h2 id="detailTitle">${esc(g.name)}${g.name_missing?'（名稱待補）':''}</h2><div class="detail-date">${esc(overview.trade_date)} · 快照 ${esc(snapshot().time)}</div><div class="detail-pct ${V.bucket(g.avg_change_pct,overview.change_scale).side}">${esc(fmt(g.avg_change_pct))}</div><div class="detail-stats"><div><small>活躍度</small><b>${esc(num(g.activity_score))}</b></div><div><small>成交占比</small><b>${esc(share(g.turnover_share))}</b></div><div><small>升降溫</small><b>${esc(g.activity_change==null?missing:(g.activity_change>0?'+':'')+g.activity_change+' 分')}</b></div><div><small>上漲 / 下跌 / 平盤</small><b>${esc(counts(g))}</b></div></div>`}
function hover(id,el){if(mobile()||selected)return;const g=snapshot()?.groups.find(g=>g.group_id===id);if(!g)return;hoverId=id;$('hoverCard').innerHTML=`<strong>${esc(g.name)}</strong><span class="${V.bucket(g.avg_change_pct,overview.change_scale).side}">${esc(fmt(g.avg_change_pct))}</span><div>活躍度 ${esc(num(g.activity_score))} · 升降溫 ${g.activity_change>0?'+':''}${esc(num(g.activity_change,' 分'))}</div><div>成交占比 ${esc(share(g.turnover_share))}</div><div>漲 / 跌 / 平 ${esc(counts(g))}</div><small>點擊查看成分股與走勢</small>`;$('hoverCard').hidden=false;const host=$('sceneWrap').getBoundingClientRect(),box=el.getBoundingClientRect();$('hoverCard').style.left=Math.max(8,Math.min(host.width-248,box.right-host.left+12))+'px';$('hoverCard').style.top=Math.max(8,Math.min(host.height-$('hoverCard').offsetHeight-8,box.top-host.top))+'px'}
for(const svg of [$('galaxy'),$('expandedGalaxy')]){svg.onclick=e=>{const el=e.target.closest('.planet');if(el)openDetail(el.dataset.group,el)};svg.onkeydown=e=>{const el=e.target.closest('.planet');if(el&&['Enter',' '].includes(e.key)){e.preventDefault();openDetail(el.dataset.group,el)}};svg.onpointerover=e=>{const el=e.target.closest('.planet');if(el&&hoverId!==el.dataset.group)hover(el.dataset.group,el)};svg.onpointerout=e=>{const from=e.target.closest('.planet'),to=e.relatedTarget?.closest?.('.planet');if(from!==to)hideHover()};svg.onfocusin=e=>{const el=e.target.closest('.planet');if(el)hover(el.dataset.group,el)};svg.onfocusout=hideHover}
function positionDetail(){const panel=$('detail');if(mobile()){document.body.append(panel);panel.setAttribute('aria-modal','true');$('detailBackdrop').hidden=!selected;document.querySelector('main').inert=!!selected;document.querySelector('header').inert=!!selected;document.body.style.overflow=selected?'hidden':''}else{$('highlights').append(panel);panel.setAttribute('aria-modal','false');$('detailBackdrop').hidden=true;document.querySelector('main').inert=false;document.querySelector('header').inert=false;document.body.style.overflow=''}$('highlightLists').hidden=!!selected&&!mobile()}
async function openDetail(id,origin){stop();hideHover();selected=id;lastFocus=origin||document.activeElement;detailData=null;const request=++detailRequest;positionDetail();$('detail').hidden=false;scene.select(id,chosenCluster());expandedScene.select(id,chosenCluster());renderStrip();renderWatch();const g=snapshot().groups.find(g=>g.group_id===id);$('detailBody').innerHTML=(g?stats(g):'')+'<p>讀取成分股中…</p>';$('closeDetail').focus();try{let d=detailCache.get(id);if(!d){d=await api.getGroupDetail(id);detailCache.set(id,d)}if(request!==detailRequest)return;detailData=d;renderDetail()}catch(e){if(request!==detailRequest)return;$('detailBody').innerHTML=(g?stats(g):'')+`<p class="detail-note">${esc(e.message)}</p>`}}
function renderDetail(){const g=snapshot()?.groups.find(g=>g.group_id===selected);if(!g){$('detailBody').innerHTML='<h2 id="detailTitle">此時段無此族群資料</h2>';return}const history=timeline.snapshots.slice(0,index+1).map((s,i)=>({time:s.time,i,...s.groups.find(n=>n.group_id===selected)})).filter(v=>Number.isFinite(v.activity_score)),peak=history.reduce((a,b)=>a.activity_score>=b.activity_score?a:b),points=history.map((v,i)=>(i&&history[i-1].i===v.i-1?'L':'M')+(v.i/Math.max(1,index)*280).toFixed(1)+','+(75-v.activity_score*.65).toFixed(1)).join(' ');
 $('detailBody').innerHTML=stats(g)+`<p class="detail-note">截至所選時間高峰 ${esc(peak.time)} · 活躍 ${esc(peak.activity_score)}</p><svg class="sparkline" viewBox="0 0 280 80" role="img" aria-label="截至所選時間的活躍度走勢"><path d="${points}" fill="none" stroke="currentColor" stroke-width="2"/></svg><div class="spark-times"><span>${esc(history[0].time)}</span><span>${esc(snapshot().time)}</span></div><h3>成分股</h3><p class="stock-time">${snapshot().time<detailData.data_time?'個股為 '+esc(detailData.data_time)+' 收盤時點':'個股行情時間 '+esc(detailData.data_time)} · 不隨回放</p>`+detailData.stocks.map(s=>`<button class="stock-row" data-route="stock" data-code="${esc(s.code)}"><span>${esc(s.name)}<small>${esc(s.code)} · 20 日區間 ${esc(s.range20_pos==null?'資料累積中':s.range20_pos+'%')}</small></span><span>${esc(num(s.price,' 元'))}<small class="${V.bucket(s.change_pct,overview.change_scale).side}">${esc(fmt(s.change_pct))} ↗</small></span></button>`).join('')+'<p class="detail-note">族群占比可能重疊，合計僅供參考。個股入口目前為 Demo 說明。</p>'}
function closeDetail(){++detailRequest;selected=null;detailData=null;$('detail').hidden=true;positionDetail();scene.select(null);expandedScene.select(null);if(overview)renderWatch();if(snapshot())renderStrip();if(lastFocus?.isConnected)lastFocus.focus();hideHover()}
$('closeDetail').onclick=closeDetail;$('detailBackdrop').onclick=closeDetail;
document.addEventListener('keydown',e=>{if($('detail').hidden||$('routeNotice').open)return;if(e.key==='Escape')closeDetail();if(e.key==='Tab'&&mobile()){const buttons=[...$('detail').querySelectorAll('button:not([disabled])')],first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
$('entries').innerHTML=[['selection','12 金釵選股'],['disposition','處置股'],['discussion','討論']].map(([id,label])=>`<button class="quiet-button" data-route="${id}">${label} ↗</button>`).join('');
document.addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(!b)return;const route=ROUTES[b.dataset.route];if(route){location.href=route.replace('{code}',encodeURIComponent(b.dataset.code||''));return}$('routeTitle').textContent=b.dataset.code?'個股 '+b.dataset.code:b.textContent;$('routeNotice').showModal();$('closeRoute').focus()});$('closeRoute').onclick=()=>$('routeNotice').close();
async function load(prefetched){const request=++loadId;stop();scene.stop();expandedScene.stop();clearTimeout(poll);hideHover();try{const [o,t]=await Promise.all([prefetched?Promise.resolve(prefetched):api.getMarketOverview(),api.getTimeline()]);if(request!==loadId)return;V.validate(o.change_scale);if(selected)closeDetail();detailCache.clear();overview=o;timeline=t;index=t.snapshots.length-1;expandedId=null;expandedKey='';$('clusterExpand').hidden=true;maxScores={};for(const s of t.snapshots)for(const g of s.groups)maxScores[g.group_id]=Math.max(maxScores[g.group_id]||0,g.activity_score);dayGroups=[...new Map(t.snapshots.flatMap(s=>s.groups).map(g=>[g.group_id,g])).values()];referenceShares=clusterShares(o.cluster_reference_groups||o.groups,o.clusters);layoutKey='';$('dataLabel').textContent=o.data_label;$('scenario').innerHTML=o.demo_scenarios.map(s=>`<option value="${esc(s.id)}">${esc(s.label.replaceAll('小島','星球'))}</option>`).join('');$('scenario').value=o.demo_scenario;$('marketState').textContent=o.awaiting_first_snapshot?'等待首筆':o.is_delayed?'資料延遲':({closed:'收盤回放',pre_open:'盤前 · 回放',holiday:'休市 · 回放',open:'盤中快照'}[o.market_state]);$('tradeDate').textContent=o.trade_date.replaceAll('-','.');$('poolCount').textContent=o.pool_size+' 檔活躍池';$('dataTime').textContent=o.data_time;renderSummary();renderLegend();renderRotation();renderWatch();$('empty').hidden=!!t.snapshots.length;if(t.snapshots.length)renderSnapshot(true);else{$('galaxy').innerHTML='';$('galaxy').style.height='250px';$('clusterStrip').innerHTML='';$('empty').innerHTML='<strong>等待第一筆市場快照</strong><span>資料時間 '+esc(o.data_time)+'</span>';$('visibleCount').textContent='';$('replayState').textContent='等待更新';$('currentFocus').textContent='首筆資料產生後，市場星系將會展開';$('source').textContent=o.source;renderHighlights()}$('announcement').textContent='市場資料已載入';schedulePoll()}catch(e){if(request!==loadId)return;$('marketState').textContent='載入失敗';$('empty').hidden=false;$('empty').innerHTML='<strong>暫時無法讀取市場</strong><span>'+esc(e.message)+'</span><button id="retryLoad">重新讀取</button>';$('retryLoad').onclick=()=>load();console.error(e)}}
function schedulePoll(){clearTimeout(poll);if(document.hidden||overview?.market_state!=='open')return;poll=setTimeout(async()=>{try{const next=await api.getMarketOverview();if(['trade_date','data_time','market_state','is_delayed','awaiting_first_snapshot'].some(k=>next[k]!==overview[k]))await load(next)}catch(e){$('marketState').textContent='更新失敗 · 保留快照'}schedulePoll()},60000)}
$('scenario').onchange=async e=>{await api.setScenario(e.target.value);await load()};
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();scene.stop();expandedScene.stop();clearTimeout(poll);hideHover()}else{if(snapshot())renderSnapshot(true);schedulePoll()}});
new ResizeObserver(()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(snapshot()){renderScene(true);renderRotation();renderHighlights();positionDetail()}},120)}).observe($('sceneWrap'));
function renderedAudit(){const collisions=[],outside=[],labelProximity=[];for(const svg of [$('galaxy'),...(!$('clusterExpand').hidden?[$('expandedGalaxy')]:[])]){const inv=svg.getCTM()?.inverse();if(!inv)continue;const box=el=>{const b=el.getBBox(),m=inv.multiply(el.getCTM()),a=new DOMPoint(b.x,b.y).matrixTransform(m),z=new DOMPoint(b.x+b.width,b.y+b.height).matrixTransform(m);return {x:a.x,y:a.y,w:z.x-a.x,h:z.y-a.y}},texts=[...svg.querySelectorAll('.planet-label,.planet-pct,.cluster-heading')].filter(el=>el.textContent.trim()&&!el.closest('.absent')&&getComputedStyle(el).visibility!=='hidden').map(el=>({id:(el.closest('[data-group]')?.dataset.group||el.closest('[data-cluster]')?.dataset.cluster)+':'+el.classList[0],owner:el.closest('[data-group]')?.dataset.group,external:el.classList.contains('planet-label')&&!el.closest('.internal-label'),...box(el)})),circles=[...svg.querySelectorAll('.planet:not(.absent) .planet-body')].map(el=>{const b=box(el);return {id:el.parentElement.dataset.group,cx:b.x+b.w/2,cy:b.y+b.h/2,rEnvelope:b.w/2}}),vb=svg.viewBox.baseVal,overlap=(a,b)=>a.x<b.x+b.w-.2&&a.x+a.w>b.x+.2&&a.y<b.y+b.h-.2&&a.y+a.h>b.y+.2;for(let i=0;i<texts.length;i++){const a=texts[i];if(a.x<-.2||a.y<-.2||a.x+a.w>vb.width+.2||a.y+a.h>vb.height+.2)outside.push(a.id);for(const b of texts.slice(i+1))if(overlap(a,b))collisions.push([a.id,b.id]);for(const b of circles)if(a.owner!==b.id&&L.circleRect(b,a))collisions.push([a.id,b.id]);if(a.external){const own=circles.find(c=>c.id===a.owner);if(own)for(const other of circles.filter(c=>c.id!==a.owner)){const ownDistance=L.distance(own,a),otherDistance=L.distance(other,a);if(ownDistance>=otherDistance*.6)labelProximity.push({label:a.id,other:other.id,ownDistance,otherDistance})}}}}
 return {collisions,outside,labelProximity};}
window.MarketDebug=Object.freeze({renderedAudit,getLayout:async()=>structuredClone(scene.getLayout()),audit:async()=>scene.getLayout()?L.audit(scene.getLayout()):null,getState:async()=>{const nodes=[...$('galaxy').querySelectorAll('.planet:not(.absent)')],active=[...document.querySelectorAll('#galaxy .planet:not(.absent),#clusterExpand:not([hidden]) .planet:not(.absent)')].filter(el=>Number(el.dataset.score)>=20),labeled=active.filter(el=>el.querySelector('.planet-label').textContent&&getComputedStyle(el.querySelector('.planet-label')).visibility!=='hidden');return {builds,transitions,index,playing:!!playing,mobile:mobile(),lite,time:snapshot()?.time,scale:overview?.change_scale,fullClusters:scene.getLayout()?.fullClusters||[],fullClusterSummary:(scene.getLayout()?.clusters||[]).map(c=>({id:c.id,name:c.name,referenceShare:referenceShares[c.id]})),fullClusterShare:(scene.getLayout()?.fullClusters||[]).reduce((sum,id)=>sum+(referenceShares[id]??0),0),focusClusters:[...new Set(ranks(snapshot()?.groups||[]).slice(0,5).map(g=>g.cluster_id))],galaxyHeight:$('galaxy').getBoundingClientRect().height+$('clusterStrip').getBoundingClientRect().height,stripClusters:scene.getLayout()?.strip.map(c=>c.clusterId)||[],activeLabels:{eligible:active.length,labeled:labeled.length,ratio:active.length?labeled.length/active.length:1,missing:active.filter(el=>!labeled.includes(el)).map(el=>el.dataset.group)},labeledRatio:nodes.length?nodes.filter(el=>el.querySelector('.planet-label').textContent).length/nodes.length:0,visible:nodes.map(el=>el.dataset.group),union:dayGroups.length}},setIndex:async i=>setIndex(i)});
if(document.fonts?.ready)document.fonts.ready.then(()=>{layoutKey='';expandedKey='';if(snapshot())renderScene(true)});
load();
})();
