window.MarketVisuals=(()=>{
const HEAT_THRESHOLD=5;
function validate(s){const v=['flat','small','normal','strong'].map(k=>s?.[k]);if(v.some((n,i)=>!Number.isFinite(n)||n<=0||(i&&n<=v[i-1])))throw Error('資料缺少有效的固定漲跌色階');return s}
function bucket(change,s){validate(s);const n=Math.abs(change);if(change==null||n<s.flat)return {key:'flat',side:'flat',level:0};const side=change>=0?'up':'down',level=n<s.small?1:n<s.normal?2:n<s.strong?3:4;return {key:side+'-'+level,side,level}}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Decorative hub-to-member line, drawn edge to edge. It is skipped when it would pass another disk, a
// label (including where a label slides as its disk shrinks) or a heading, so it never reads as a label leader.
function association(a,b,layout){const d=Math.hypot(b.cx-a.cx,b.cy-a.cy);if(d<=a.rEnvelope+b.rEnvelope+8)return null;const ux=(b.cx-a.cx)/d,uy=(b.cy-a.cy)/d,x1=a.cx+ux*(a.rEnvelope+3),y1=a.cy+uy*(a.rEnvelope+3),x2=b.cx-ux*(b.rEnvelope+3),y2=b.cy-uy*(b.rEnvelope+3),len=Math.hypot(x2-x1,y2-y1);
 const boxes=[...layout.nodes.filter(n=>n.slot).map(n=>{const s=n.slot,t=s.travel||0,x=Math.min(s.x,s.x+(s.dx||0)*t),y=Math.min(s.y,s.y+(s.dy||0)*t);return {x:x-4,y:y-4,w:s.w+Math.abs(s.dx||0)*t+8,h:s.h+Math.abs(s.dy||0)*t+8}}),...layout.clusters.map(c=>({x:c.header.x-4,y:c.header.y-4,w:c.header.w+8,h:c.header.h+8}))];
 for(let s=0;s<=len;s+=3){const x=x1+ux*s,y=y1+uy*s;if(boxes.some(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h)||layout.nodes.some(n=>n!==a&&n!==b&&Math.hypot(n.cx-x,n.cy-y)<n.rEnvelope+4))return null}return [x1,y1,x2,y2]}
function create(svg){let layout,elements=new Map(),raf=null,token=0,lite=false,mobile=false,selected=null;const prefix=svg.id+'-';
 function stop(){if(raf!==null)cancelAnimationFrame(raf);raf=null;token++}
 function select(id,cluster){selected=id;const chosen=cluster||layout?.nodes.find(n=>n.id===id)?.cluster;elements.forEach(e=>{e.root.classList.toggle('dim',!!id&&e.node.cluster!==chosen);e.root.classList.toggle('selected',e.node.id===id);e.root.setAttribute('aria-pressed',String(e.node.id===id))});for(const g of svg.querySelectorAll('.cluster'))g.classList.toggle('dim',!!id&&g.dataset.cluster!==chosen)}
 function build(next,isLite,isMobile){stop();layout=next;lite=isLite;mobile=isMobile;svg.setAttribute('viewBox',`0 0 ${next.width} ${next.height}`);svg.style.height=next.height+'px';let h='<defs>';
 for(const key of ['flat',...['up','down'].flatMap(s=>[1,2,3,4].map(i=>s+'-'+i))])h+=`<radialGradient id="${prefix+key}" cx="30%" cy="25%" r="80%"><stop stop-color="var(--${key}-rim)"/><stop offset=".35" stop-color="var(--${key}-top)"/><stop offset="1" stop-color="var(--${key}-base)"/></radialGradient>`;
 h+=`<radialGradient id="${prefix}nebula"><stop stop-color="var(--accent)" stop-opacity=".1"/><stop offset="1" stop-color="var(--accent)" stop-opacity="0"/></radialGradient></defs>`;
 if(!lite&&!mobile)for(let i=0;i<40;i++)h+=`<circle class="star" cx="${(i*137.17)%next.width}" cy="${(i*97.3)%next.height}" r="${i%3===0?1.2:.6}"/>`;
 for(const c of next.clusters){h+=`<g class="cluster" data-cluster="${esc(c.id)}"><ellipse class="cluster-outline" cx="${c.x}" cy="${c.y}" rx="${c.rx}" ry="${c.ry}" fill="url(#${prefix}nebula)"/><text class="cluster-heading" x="${c.header.x}" y="${c.header.y+11}" font-size="11"><tspan>${esc(c.name)}</tspan><tspan class="cluster-share" x="${c.header.x+(mobile?MarketLayout.measure(c.name,11)+8:0)}" dy="${mobile?0:16}"></tspan></text>`;
 if(!lite){const ns=next.nodes.filter(n=>n.cluster===c.id);for(const n of ns.slice(1)){const a=association(ns[0],n,next);if(a)h+=`<line class="association" data-from="${esc(ns[0].id)}" data-to="${esc(n.id)}" x1="${a[0]}" y1="${a[1]}" x2="${a[2]}" y2="${a[3]}"/>`}}
 h+='</g>'}
 for(const n of next.nodes)h+=`<g class="planet" data-group="${esc(n.id)}" data-cluster="${esc(n.cluster)}" tabindex="0" role="button" aria-pressed="false" transform="translate(${n.cx} ${n.cy})"><title>${esc(n.name)}</title><circle class="planet-hit" r="${Math.max(22,n.rEnvelope+5)}"/><line class="label-leader"/><circle class="planet-prior"/><circle class="planet-body"/><circle class="halo halo-one"/><circle class="halo halo-two"/><text class="planet-label" text-anchor="middle" font-size="11"></text><text class="planet-pct" text-anchor="middle" font-size="11" y="17"></text></g>`;
 svg.innerHTML=h;elements.clear();for(const root of svg.querySelectorAll('.planet')){const node=next.nodes.find(n=>n.id===root.dataset.group);elements.set(node.id,{root,node,r:0,body:root.querySelector('.planet-body'),prior:root.querySelector('.planet-prior'),label:root.querySelector('.planet-label'),pct:root.querySelector('.planet-pct')})}select(selected);
 }
 function update(groups,colorScale,{instant=false}={}){validate(colorScale);stop();const t=token,present=new Map(groups.map(g=>[g.group_id,g])),targets=[];
 for(const [id,e] of elements){const g=present.get(id);if(!g){e.root.setAttribute('tabindex','-1');e.root.classList.add('absent');e.root.style.pointerEvents='none';e.root.setAttribute('aria-hidden','true');continue}e.root.classList.remove('absent');e.root.style.pointerEvents='';e.root.removeAttribute('aria-hidden');e.root.setAttribute('tabindex','0');const key=bucket(g.avg_change_pct,colorScale).key,r=MarketLayout.radius(g.activity_score,mobile,layout.scale);e.prior.setAttribute('fill',e.body.getAttribute('fill')||'none');e.prior.style.setProperty('--planet-solid',e.body.style.getPropertyValue('--planet-solid'));e.body.style.setProperty('--planet-solid',`var(--${key}-top)`);e.body.setAttribute('fill',`url(#${prefix+key})`);e.root.dataset.score=g.activity_score;e.root.querySelector('title').textContent=g.name+' · 活躍度 '+g.activity_score;e.root.setAttribute('aria-label',g.name+'，活躍度 '+g.activity_score+'，按 Enter 查看詳情');e.root.classList.toggle('heating',g.activity_change>=HEAT_THRESHOLD);
 const inner=MarketLayout.measure(g.name,11)<=r*1.65&&r>=23&&(instant||lite||MarketLayout.measure(g.name,11)<=e.r*1.65&&e.r>=23),allowed=!mobile||g.activity_score>=20;
 e.label.textContent='';e.pct.textContent='';e.root.querySelector('.label-leader').style.display='none';e.pct.setAttribute('x','0');e.pct.setAttribute('y','17');
 // A reserved external label remains safe through every intermediate radius.
 if(allowed&&inner){e.label.setAttribute('text-anchor','middle');e.label.setAttribute('x','0');e.label.setAttribute('y','-3');e.label.textContent=g.name;e.pct.textContent=g.avg_change_pct==null?'':(g.avg_change_pct>0?'+':'')+g.avg_change_pct.toFixed(2)+'%'}
 else if(allowed&&e.node.slot){const s=e.node.slot,right=s.x>=e.node.cx,left=s.x+s.w<=e.node.cx,ax=(right?s.x:left?s.x+s.w:s.x+s.w/2)-e.node.cx;e.label.setAttribute('text-anchor',right?'start':left?'end':'middle');e.label.setAttribute('x',ax);e.label.setAttribute('y',s.y+11-e.node.cy);e.label.innerHTML=[...e.node.lines,...(mobile?[]:[g.avg_change_pct==null?'資料準備中':(g.avg_change_pct>0?'+':'')+g.avg_change_pct.toFixed(2)+'%'])].map((line,i)=>`<tspan x="${ax}" dy="${i?15:0}">${esc(line)}</tspan>`).join('');const line=e.root.querySelector('.label-leader'),lx=Math.max(s.x,Math.min(e.node.cx,s.x+s.w))-e.node.cx,ly=Math.max(s.y,Math.min(e.node.cy,s.y+s.h))-e.node.cy,d=Math.hypot(lx,ly);line.style.display='';line.setAttribute('x1',lx/d*(r+2));line.setAttribute('y1',ly/d*(r+2));line.setAttribute('x2',lx);line.setAttribute('y2',ly)}
 e.root.classList.toggle('internal-label',allowed&&inner);targets.push({e,from:e.r,to:r,inner:allowed&&inner});
 }
 // A decorative line to an absent planet would point at empty space, so it hides with that planet.
 for(const line of svg.querySelectorAll('.association'))line.style.display=present.has(line.dataset.from)&&present.has(line.dataset.to)?'':'none';
 const start=performance.now();function frame(now){if(t!==token)return;const p=instant||lite?1:Math.min(1,(now-start)/520),q=1-(1-p)**3;for(const {e,from,to,inner} of targets){e.r=from+(to-from)*q;if(!inner&&e.node.slot){const s=e.node.slot,n=e.node,delta=n.rEnvelope-e.r,dx=s.x>=n.cx? -delta:s.x+s.w<=n.cx?delta:0,dy=s.y>=n.cy?-delta:s.y+s.h<=n.cy?delta:0;e.label.setAttribute('transform',`translate(${dx} ${dy})`);const line=e.root.querySelector('.label-leader'),lx=Math.max(s.x+dx,Math.min(n.cx,s.x+dx+s.w))-n.cx,ly=Math.max(s.y+dy,Math.min(n.cy,s.y+dy+s.h))-n.cy,d=Math.hypot(lx,ly);line.setAttribute('x1',lx/d*(e.r+2));line.setAttribute('y1',ly/d*(e.r+2));line.setAttribute('x2',lx);line.setAttribute('y2',ly)}else e.label.removeAttribute('transform');e.body.setAttribute('r',e.r);e.prior.setAttribute('r',e.r);e.body.style.opacity=q;e.prior.style.opacity=1-q;e.root.querySelector('.halo-one').setAttribute('r',e.r+4);e.root.querySelector('.halo-two').setAttribute('r',e.r+8);if(inner){const safe=MarketLayout.measure(e.label.textContent,11)<=e.r*1.65&&e.r>=23;e.label.style.visibility=safe?'':'hidden';e.pct.style.visibility=safe?'':'hidden'}else{e.label.style.visibility='';e.pct.style.visibility=''}}if(p<1)raf=requestAnimationFrame(frame);else raf=null}frame(start);select(selected);
 }
 function shares(values){for(const el of svg.querySelectorAll('.cluster-share')){const value=values[el.closest('[data-cluster]').dataset.cluster];el.textContent=value==null?'成交占比：資料準備中':'成交 '+(value*100).toFixed(1)+'%'}}
 return {build,update,select,stop,shares,getLayout:()=>layout};
}
return {validate,bucket,esc,create,HEAT_THRESHOLD};
})();
