/* SoftGlow Common v1.0 — Search, Bookmark, Share, Print
 * Dependencies: Fuse.js (loaded lazily on first search open)
 * Data: /search-index.json (auto-generated by Generator)
 * Page meta: <meta name="sg-slug">, <meta name="sg-type">, <meta name="sg-lang">
 */
(function(){
  'use strict';

  // ---------------------------------------------------------------------------
  // Page meta
  // ---------------------------------------------------------------------------
  var META = {
    slug: _metaVal('sg-slug'),
    type: _metaVal('sg-type'),
    lang: _metaVal('sg-lang') || 'zh-TW'
  };

  function _metaVal(name) {
    var el = document.querySelector('meta[name="' + name + '"]');
    return el ? el.getAttribute('content') : '';
  }

  // ---------------------------------------------------------------------------
  // Toast
  // ---------------------------------------------------------------------------
  var _toastEl = null;
  var _toastTimer = null;

  function toast(msg) {
    if (!_toastEl) {
      _toastEl = document.createElement('div');
      _toastEl.className = 'sg-toast';
      document.body.appendChild(_toastEl);
    }
    _toastEl.textContent = msg;
    _toastEl.classList.add('show');
    clearTimeout(_toastTimer);
    _toastTimer = setTimeout(function(){ _toastEl.classList.remove('show'); }, 2000);
  }

  // ---------------------------------------------------------------------------
  // Search
  // ---------------------------------------------------------------------------
  var _searchOverlay, _searchInput, _searchResults;
  var _fuse = null;
  var _searchIndex = null;
  var _fuseLoaded = false;

  function initSearch() {
    _searchOverlay = document.getElementById('sgSearchOverlay');
    _searchInput = document.getElementById('sgSearchInput');
    _searchResults = document.getElementById('sgSearchResults');
    if (!_searchOverlay || !_searchInput || !_searchResults) return;

    // Close on overlay click
    _searchOverlay.addEventListener('click', function(e) {
      if (e.target === _searchOverlay) closeSearch();
    });

    // Close on ESC
    document.addEventListener('keydown', function(e) {
      if (e.key === 'Escape' && _searchOverlay.classList.contains('open')) closeSearch();
    });

    // Input handler
    _searchInput.addEventListener('input', function() {
      doSearch(this.value.trim());
    });
  }

  function openSearch() {
    if (!_searchOverlay) return;
    _searchOverlay.classList.add('open');
    _searchInput.value = '';
    _searchInput.focus();
    _searchResults.innerHTML = '<div class="search-empty">' + _searchHint() + '</div>';

    // Lazy load Fuse.js + search index
    if (!_fuseLoaded) {
      _fuseLoaded = true;
      loadFuse();
    }
  }

  function closeSearch() {
    if (_searchOverlay) _searchOverlay.classList.remove('open');
  }

  function _searchHint() {
    var hints = {
      'zh-TW': '輸入關鍵字搜尋工具、型態、文章…',
      'zh-CN': '输入关键字搜索工具、形态、文章…',
      'en': 'Search tools, patterns, articles…',
      'ja': 'ツール、パターン、記事を検索…',
      'ko': '도구, 패턴, 기사 검색…',
      'de': 'Tools, Muster, Artikel suchen…',
      'fr': 'Rechercher outils, patterns, articles…',
      'es': 'Buscar herramientas, patrones, artículos…',
      'pt': 'Pesquisar ferramentas, padrões, artigos…',
      'id': 'Cari alat, pola, artikel…'
    };
    return hints[META.lang] || hints['en'];
  }

  function loadFuse() {
    // Load Fuse.js from CDN
    var script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/fuse.js/7.0.0/fuse.min.js';
    script.onload = function() {
      // Load search index
      fetch('/common/search-index.json')
        .then(function(r){ return r.json(); })
        .then(function(data){
          _searchIndex = data;
          _fuse = new Fuse(data, {
            keys: ['names.' + META.lang, 'names.en', 'slug'],
            threshold: 0.3,
            limit: 10
          });
        })
        .catch(function(e){ console.warn('search-index.json load failed:', e); });
    };
    document.head.appendChild(script);
  }

  function doSearch(query) {
    if (!query) {
      _searchResults.innerHTML = '<div class="search-empty">' + _searchHint() + '</div>';
      return;
    }
    if (!_fuse) {
      _searchResults.innerHTML = '<div class="search-empty">Loading…</div>';
      return;
    }

    var results = _fuse.search(query);
    if (!results.length) {
      _searchResults.innerHTML = '<div class="search-empty">No results</div>';
      return;
    }

    var html = '';
    var typeLabels = _typeLabels();
    results.slice(0, 10).forEach(function(r) {
      var item = r.item;
      var title = (item.names && item.names[META.lang]) || (item.names && item.names['en']) || item.slug;
      var url = _buildUrl(item);
      var typeLabel = typeLabels[item.type] || item.type;
      html += '<div class="search-item" onclick="window.location.href=\'' + url + '\'">' +
              '<span class="search-item-title">' + _esc(title) + '</span>' +
              '<span class="search-item-type">' + typeLabel + '</span></div>';
    });
    _searchResults.innerHTML = html;
  }

  function _typeLabels() {
    var labels = {
      'zh-TW': {tool:'工具', pattern:'型態', blog:'文章'},
      'zh-CN': {tool:'工具', pattern:'形态', blog:'文章'},
      'en': {tool:'Tool', pattern:'Pattern', blog:'Article'},
      'ja': {tool:'ツール', pattern:'パターン', blog:'記事'},
      'ko': {tool:'도구', pattern:'패턴', blog:'기사'},
      'de': {tool:'Tool', pattern:'Muster', blog:'Artikel'},
      'fr': {tool:'Outil', pattern:'Pattern', blog:'Article'},
      'es': {tool:'Herramienta', pattern:'Patrón', blog:'Artículo'},
      'pt': {tool:'Ferramenta', pattern:'Padrão', blog:'Artigo'},
      'id': {tool:'Alat', pattern:'Pola', blog:'Artikel'}
    };
    return labels[META.lang] || labels['en'];
  }

  function _buildUrl(item) {
    var lang = META.lang;
    var prefix = '';
    if (item.type === 'tool') prefix = '/tools/';
    else if (item.type === 'pattern') prefix = '/patterns/';
    else if (item.type === 'blog') prefix = '/blog/';
    else if (item.type === 'comparison') prefix = '/comparisons/';

    if (lang === 'zh-TW') return prefix + item.slug + '.html';
    return prefix + lang + '/' + item.slug + '.html';
  }

  // ---------------------------------------------------------------------------
  // Bookmark
  // ---------------------------------------------------------------------------
  var BM_KEY = 'sg_bookmarks';
  var _bmPanel;

  function initBookmark() {
    _bmPanel = document.getElementById('sgBmPanel');
    updateBookmarkBtn();
  }

  function getBookmarks() {
    try {
      return JSON.parse(localStorage.getItem(BM_KEY) || '[]');
    } catch(e) { return []; }
  }

  function saveBookmarks(list) {
    localStorage.setItem(BM_KEY, JSON.stringify(list));
  }

  function isBookmarked() {
    if (!META.slug) return false;
    return getBookmarks().some(function(b){ return b.slug === META.slug && b.lang === META.lang; });
  }

  function toggleBookmark() {
    if (!META.slug) return;
    var list = getBookmarks();
    var idx = list.findIndex(function(b){ return b.slug === META.slug && b.lang === META.lang; });

    if (idx >= 0) {
      list.splice(idx, 1);
      toast(_bmToasts().removed);
    } else {
      list.unshift({
        slug: META.slug,
        type: META.type,
        lang: META.lang,
        title: document.title.split('|')[0].split('—')[0].trim(),
        url: window.location.pathname,
        time: Date.now()
      });
      toast(_bmToasts().added);
    }
    saveBookmarks(list);
    updateBookmarkBtn();
  }

  function _bmToasts() {
    var t = {
      'zh-TW': {added:'已收藏', removed:'已取消收藏'},
      'zh-CN': {added:'已收藏', removed:'已取消收藏'},
      'en': {added:'Bookmarked', removed:'Bookmark removed'},
      'ja': {added:'ブックマークしました', removed:'ブックマーク解除'},
      'ko': {added:'북마크 추가', removed:'북마크 제거'}
    };
    return t[META.lang] || t['en'];
  }

  function updateBookmarkBtn() {
    var btn = document.getElementById('sgBmBtn');
    if (!btn) return;
    if (isBookmarked()) {
      btn.classList.add('bookmarked');
    } else {
      btn.classList.remove('bookmarked');
    }
  }

  function toggleBmPanel() {
    if (!_bmPanel) return;
    if (_bmPanel.classList.contains('open')) {
      _bmPanel.classList.remove('open');
      return;
    }
    renderBmPanel();
    _bmPanel.classList.add('open');

    // Close on outside click
    setTimeout(function(){
      document.addEventListener('click', _closeBmOutside, {once:true});
    }, 50);
  }

  function _closeBmOutside(e) {
    if (_bmPanel && !_bmPanel.contains(e.target)) {
      _bmPanel.classList.remove('open');
    }
  }

  function renderBmPanel() {
    var list = getBookmarks();
    var container = document.getElementById('sgBmList');
    if (!container) return;

    if (!list.length) {
      var emptyMsg = META.lang === 'zh-TW' ? '尚無收藏' : (META.lang === 'zh-CN' ? '暂无收藏' : 'No bookmarks yet');
      container.innerHTML = '<div class="bm-empty">' + emptyMsg + '</div>';
      return;
    }

    var typeLabels = _typeLabels();
    var html = '';
    list.forEach(function(b, i) {
      var typeLabel = typeLabels[b.type] || b.type;
      html += '<div class="bm-item">' +
              '<a href="' + _esc(b.url) + '">' + _esc(b.title) + '</a>' +
              '<span class="bm-item-type">' + typeLabel + '</span>' +
              '<button class="bm-remove" onclick="window._sgRemoveBm(' + i + ')" title="Remove">×</button></div>';
    });
    container.innerHTML = html;
  }

  window._sgRemoveBm = function(idx) {
    var list = getBookmarks();
    list.splice(idx, 1);
    saveBookmarks(list);
    renderBmPanel();
    updateBookmarkBtn();
  };

  window._sgClearBm = function() {
    saveBookmarks([]);
    renderBmPanel();
    updateBookmarkBtn();
    toast(META.lang === 'zh-TW' ? '已清除所有收藏' : 'All bookmarks cleared');
  };

  // ---------------------------------------------------------------------------
  // Share
  // ---------------------------------------------------------------------------
  function doShare() {
    var title = document.title;
    var url = window.location.href;

    if (navigator.share) {
      navigator.share({title: title, url: url}).catch(function(){});
    } else {
      // Fallback: copy URL
      navigator.clipboard.writeText(url).then(function(){
        toast(META.lang === 'zh-TW' ? '已複製連結' : 'Link copied');
      }).catch(function(){
        toast('Copy failed');
      });
    }
  }

  // ---------------------------------------------------------------------------
  // Print
  // ---------------------------------------------------------------------------
  function doPrint() {
    window.print();
  }

  // ---------------------------------------------------------------------------
  // HTML escape
  // ---------------------------------------------------------------------------
  function _esc(s) {
    var d = document.createElement('div');
    d.textContent = s;
    return d.innerHTML;
  }

  // ---------------------------------------------------------------------------
  // Init
  // ---------------------------------------------------------------------------
  document.addEventListener('DOMContentLoaded', function() {
    initSearch();
    initBookmark();
  });

  // Expose to global for onclick handlers in template
  window.sgOpenSearch = openSearch;
  window.sgCloseSearch = closeSearch;
  window.sgToggleBookmark = toggleBookmark;
  window.sgToggleBmPanel = toggleBmPanel;
  window.sgShare = doShare;
  window.sgPrint = doPrint;

})();
